### ISSUE TITLE
LICENSE for module is missing

### ISSUE THREAD

**Issue by dfch** [DollarUnderscore/Infoblox-PowerShell-Module#3]
@DollarUnderscore some time ago I also created a [PowerShell module for the Infoblox REST API](https://github.com/dfch/biz.dfch.PS.Ipam.Infoblox.Api) and there have provided basic functionality. I looked at your repo and it seems rather stale, so my question is:

* what is your licensing model (e.g. Apache 2.0)?
* can I reuse some of your code and add it to our repo?

Thanks for your reply! Ronald

**Comment by DollarUnderscore** [comment]
Yes, I hoped that I would receive some help building this but even if the interest about having a PowerShell module for Infoblox has been pretty high, it's hard to find someone willing to invest some time and effort into it. It has been on my "to do"-list for a long time now, but sadly I lost access to my Infoblox test environment a while back and haven't got around setting a new one up.

Long story short, I just want to this help the overall community and haven't given much thought about a license, but I'll try to fix that right away! And in any case, feel free to reuse the code in your own repo which I will definitely take a look at!

**Comment by AWahlqvist** [comment]
Added MIT license.

**Comment by dfch** [comment]
cool and thanks for the quick reply! I will give you an update once I have incorporated some of your stuff.

regarding an Infoblox test environment: you can always use the OVF-based trial version from Infoblox that is set up really fast and easy and is good for testing.

**Comment by AWahlqvist** [comment]
Sounds good, and if I get some time over I'll look into that trial version, thanks for the tip :)
