### ISSUE TITLE
Remove Host Record Errors Out

### ISSUE THREAD

**Issue by pkrishna1983** [DollarUnderscore/Infoblox-PowerShell-Module#4]
Please find the attached file which has the code and error message when I try to delete the record.I have installed the Infoblox Powershell module already.Addition of Host records works fine.I am unable pipe the _ref to Remove-IBResourceRecord.[
![remove host record](https://user-images.githubusercontent.com/31849215/30271928-24a7bc14-96c0-11e7-8a83-00ca7c784f99.JPG)
](url)

Please help.

**Comment by AWahlqvist** [comment]
Try changing "select _ref" to "select -ExpandProperty _ref", I think that will work better!

**Comment by pkrishna1983** [comment]
Worked Fine.Thank you very Much.
Regards,

Prathap
